name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-glue-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync Glue scripts to S3
        run: aws s3 sync processing/glue_jobs/ s3://${{ secrets.SCRIPTS_BUCKET }}/glue_jobs/ --delete

      - name: Confirm deploy
        run: |
          echo "Glue scripts synced to S3 successfully"
          aws s3 ls s3://${{ secrets.SCRIPTS_BUCKET }}/glue_jobs/